export const MOCK_PRODUCTS = [
  {
    id: 1,
    name: 'Oslo Lounge Chair',
    slug: 'oslo-lounge-chair',
    price: 2890,
    original_price: 3400,
    category: { id: 1, name: 'Living Room', slug: 'living-room' },
    rating: 4.8,
    reviews_count: 124,
    stock: 12,
    material: 'Full-Grain Leather',
    finish: 'Walnut',
    dimensions: '32"W × 34"D × 33"H',
    weight: '48 lbs',
    description: 'The Oslo Lounge Chair embodies Scandinavian design principles — clean lines, exceptional comfort, and masterful craftsmanship. Upholstered in full-grain leather with hand-stitched details, paired with a solid walnut frame that ages beautifully over time.',
    images: [
      'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800',
      'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800',
      'https://images.unsplash.com/photo-1567538096630-e0c55bd6374c?w=800',
    ],
    colors: ['Cognac', 'Midnight', 'Ivory'],
    is_featured: true,
    is_best_seller: true,
    tags: ['Chair', 'Leather', 'Lounge'],
  },
  {
    id: 2,
    name: 'Maren Sectional Sofa',
    slug: 'maren-sectional-sofa',
    price: 6490,
    original_price: null,
    category: { id: 1, name: 'Living Room', slug: 'living-room' },
    rating: 4.9,
    reviews_count: 89,
    stock: 5,
    material: 'Belgian Linen',
    finish: 'Natural Oak',
    dimensions: '112"W × 68"D × 32"H',
    weight: '220 lbs',
    description: 'Our most-loved sofa, the Maren Sectional redefines lounging luxury. Crafted with sustainably sourced Belgian linen and a kiln-dried hardwood frame, this is furniture designed for generations.',
    images: [
      'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800',
      'https://images.unsplash.com/photo-1618219908412-a29a1bb7b86e?w=800',
      'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800',
    ],
    colors: ['Sand', 'Slate', 'Chalk'],
    is_featured: true,
    is_best_seller: true,
    tags: ['Sofa', 'Sectional', 'Linen'],
  },
  {
    id: 3,
    name: 'Ember Coffee Table',
    slug: 'ember-coffee-table',
    price: 1280,
    original_price: 1490,
    category: { id: 1, name: 'Living Room', slug: 'living-room' },
    rating: 4.7,
    reviews_count: 56,
    stock: 18,
    material: 'Solid Travertine & Brass',
    finish: 'Antique Brass',
    dimensions: '48"W × 24"D × 16"H',
    weight: '85 lbs',
    description: 'The Ember Coffee Table pairs bookmatched travertine with hand-forged brass legs, creating a sculptural centerpiece that commands every room it graces.',
    images: [
      'https://images.unsplash.com/photo-1567538096630-e0c55bd6374c?w=800',
      'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800',
    ],
    colors: ['Travertine / Brass', 'Marble / Chrome'],
    is_featured: true,
    is_best_seller: false,
    tags: ['Table', 'Stone', 'Coffee Table'],
  },
  {
    id: 4,
    name: 'Vela Dining Table',
    slug: 'vela-dining-table',
    price: 4200,
    original_price: null,
    category: { id: 2, name: 'Dining', slug: 'dining' },
    rating: 4.9,
    reviews_count: 72,
    stock: 8,
    material: 'Solid White Oak',
    finish: 'Natural',
    dimensions: '84"W × 40"D × 30"H',
    weight: '145 lbs',
    description: 'The Vela Dining Table is a testament to the beauty of natural wood. Each table features a uniquely grained solid white oak top, hand-finished to reveal the wood\'s natural character.',
    images: [
      'https://images.unsplash.com/photo-1617806118233-18e1de247200?w=800',
      'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800',
    ],
    colors: ['Natural Oak', 'Dark Walnut', 'White'],
    is_featured: true,
    is_best_seller: true,
    tags: ['Table', 'Dining', 'Oak'],
  },
  {
    id: 5,
    name: 'Haven Bed Frame',
    slug: 'haven-bed-frame',
    price: 3890,
    original_price: null,
    category: { id: 3, name: 'Bedroom', slug: 'bedroom' },
    rating: 4.8,
    reviews_count: 143,
    stock: 10,
    material: 'Bouclé & Solid Walnut',
    finish: 'Dark Walnut',
    dimensions: 'King: 80"W × 86"D × 56"H',
    weight: '185 lbs',
    description: 'The Haven Bed Frame\'s high upholstered headboard creates a sanctuary-like atmosphere in any bedroom. Wrapped in plush bouclé fabric over a solid walnut base.',
    images: [
      'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800',
      'https://images.unsplash.com/photo-1618219908412-a29a1bb7b86e?w=800',
    ],
    colors: ['Oatmeal Bouclé', 'Charcoal Bouclé', 'Sage'],
    is_featured: true,
    is_best_seller: true,
    tags: ['Bed', 'Bedroom', 'Upholstered'],
  },
  {
    id: 6,
    name: 'Studio Writing Desk',
    slug: 'studio-writing-desk',
    price: 1680,
    original_price: 1990,
    category: { id: 4, name: 'Office', slug: 'office' },
    rating: 4.6,
    reviews_count: 38,
    stock: 15,
    material: 'Solid Walnut',
    finish: 'Oil Finish',
    dimensions: '60"W × 28"D × 30"H',
    weight: '75 lbs',
    description: 'A desk worthy of your best ideas. The Studio Writing Desk combines a minimalist silhouette with functional details — hidden cable management, leather-lined drawer, and solid walnut construction.',
    images: [
      'https://images.unsplash.com/photo-1593062096033-9a26b09da705?w=800',
      'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800',
    ],
    colors: ['Dark Walnut', 'Natural'],
    is_featured: false,
    is_best_seller: false,
    tags: ['Desk', 'Office', 'Walnut'],
  },
  {
    id: 7,
    name: 'Arc Floor Lamp',
    slug: 'arc-floor-lamp',
    price: 890,
    original_price: null,
    category: { id: 5, name: 'Decor', slug: 'decor' },
    rating: 4.7,
    reviews_count: 91,
    stock: 25,
    material: 'Brushed Brass & Marble',
    finish: 'Brushed Brass',
    dimensions: 'H 72" × Arm: 48"',
    weight: '22 lbs',
    description: 'A sculptural presence in any room, the Arc Floor Lamp features a sweeping arm in brushed brass with a weighted Carrara marble base and an oversized linen shade.',
    images: [
      'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=800',
      'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800',
    ],
    colors: ['Brass / Linen', 'Matte Black / Linen'],
    is_featured: false,
    is_best_seller: true,
    tags: ['Lamp', 'Lighting', 'Brass'],
  },
  {
    id: 8,
    name: 'Koru Armchair',
    slug: 'koru-armchair',
    price: 1890,
    original_price: null,
    category: { id: 1, name: 'Living Room', slug: 'living-room' },
    rating: 4.5,
    reviews_count: 47,
    stock: 20,
    material: 'Velvet & Oak',
    finish: 'Natural Oak',
    dimensions: '28"W × 30"D × 32"H',
    weight: '38 lbs',
    description: 'Inspired by the Māori symbol of renewal, the Koru Armchair combines organic curves with plush velvet upholstery for a statement piece that\'s as comfortable as it is beautiful.',
    images: [
      'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800',
      'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800',
    ],
    colors: ['Forest Green', 'Terracotta', 'Dusty Blue', 'Ivory'],
    is_featured: false,
    is_best_seller: false,
    tags: ['Chair', 'Velvet', 'Accent'],
  },
]

export const MOCK_CATEGORIES = [
  { id: 1, name: 'Living Room', slug: 'living-room', image: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=600', count: 48 },
  { id: 2, name: 'Dining', slug: 'dining', image: 'https://images.unsplash.com/photo-1617806118233-18e1de247200?w=600', count: 32 },
  { id: 3, name: 'Bedroom', slug: 'bedroom', image: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=600', count: 56 },
  { id: 4, name: 'Office', slug: 'office', image: 'https://images.unsplash.com/photo-1593062096033-9a26b09da705?w=600', count: 24 },
  { id: 5, name: 'Outdoor', slug: 'outdoor', image: 'https://images.unsplash.com/photo-1600210491369-e753d80a41f3?w=600', count: 18 },
  { id: 6, name: 'Decor', slug: 'decor', image: 'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=600', count: 62 },
]

export const MOCK_REVIEWS = [
  { id: 1, user: { name: 'Sarah M.' }, rating: 5, comment: 'Absolutely stunning piece. The craftsmanship is impeccable — better than the photos. Delivery was white-glove and the team was professional. Worth every penny.', created_at: '2024-01-15' },
  { id: 2, user: { name: 'James K.' }, rating: 5, comment: 'We\'ve been searching for the perfect dining table for two years. The Vela is everything we dreamed of. The wood grain is beautiful and it seats our family of eight comfortably.', created_at: '2024-02-03' },
  { id: 3, user: { name: 'Emma L.' }, rating: 4, comment: 'Beautiful quality, arrived well-packaged. Slight delay on shipping but customer service kept us informed. Would definitely buy again.', created_at: '2024-02-20' },
]

export const MOCK_ROOMS = [
  {
    id: 1,
    title: 'Modern Sanctuary',
    subtitle: 'Living Room',
    image: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=1200',
    products: [1, 3, 7],
  },
  {
    id: 2,
    title: 'Nordic Retreat',
    subtitle: 'Bedroom',
    image: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=1200',
    products: [5],
  },
  {
    id: 3,
    title: 'Artisan\'s Table',
    subtitle: 'Dining Room',
    image: 'https://images.unsplash.com/photo-1617806118233-18e1de247200?w=1200',
    products: [4],
  },
  {
    id: 4,
    title: 'Creative Workspace',
    subtitle: 'Home Office',
    image: 'https://images.unsplash.com/photo-1593062096033-9a26b09da705?w=1200',
    products: [6],
  },
]

export const MOCK_TESTIMONIALS = [
  {
    id: 1,
    name: 'Catherine R.',
    location: 'New York, NY',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100',
    rating: 5,
    text: 'ArtisanHome transformed our apartment. Each piece feels intentional, crafted with genuine care. The Oslo Chair has become the centerpiece of our living room.',
  },
  {
    id: 2,
    name: 'David P.',
    location: 'San Francisco, CA',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100',
    rating: 5,
    text: 'After years of buying furniture that falls apart, discovering ArtisanHome was a revelation. These are heirloom pieces designed to last generations.',
  },
  {
    id: 3,
    name: 'Isabelle T.',
    location: 'Chicago, IL',
    avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100',
    rating: 5,
    text: 'The attention to detail is extraordinary. Our Maren sofa arrived perfectly packaged and the setup team was impeccable. Worth every dollar.',
  },
]
